SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

DROP TABLE IF EXISTS memo CASCADE;
DROP TABLE IF EXISTS concerner CASCADE;

CREATE TABLE compte (
	idcompte		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (idcompte),
	UNIQUE (pseudo)
);

CREATE TABLE role (
	idcompte		INT				NOT NULL,
	role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),
	PRIMARY KEY (idcompte, role),
	FOREIGN KEY (idcompte) REFERENCES compte (idcompte)
);

CREATE TABLE categorie (
	idcategorie		INT				GENERATED BY DEFAULT AS IDENTITY,
	libelle			VARCHAR(25)		NOT NULL,
	PRIMARY KEY (idcategorie)
);

CREATE TABLE personne (
	idpersonne		INT				GENERATED BY DEFAULT AS IDENTITY,
	idcategorie		INT				NOT NULL,
	nom				VARCHAR(25)  	NOT NULL,
	prenom			VARCHAR(25) 	NOT NULL,
	PRIMARY KEY (idpersonne),
 	FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie)
);

CREATE TABLE telephone (
	idtelephone		INT				GENERATED BY DEFAULT AS IDENTITY,
	idpersonne		INT			 	NOT NULL,
	Libelle			VARCHAR(25)		NOT NULL,
	Numero			VARCHAR(25)		NOT NULL,
	PRIMARY KEY (idtelephone),
	FOREIGN KEY (idpersonne) REFERENCES personne (idpersonne)
);

CREATE TABLE service (
	idservice 		INT				GENERATED BY DEFAULT AS IDENTITY,
	nom 			VARCHAR(50)		NOT NULL,
	description		VARCHAR(1000),
	anneecreation	SMALLINT,
	flagsiege		BOOLEAN			NOT NULL,
	PRIMARY KEY (idservice)
);



/*
------------------------------------------------------------
-- Table: Utilisateur
------------------------------------------------------------
CREATE TABLE utilisateur(
	idutilisateur    INT 			 GENERATED BY DEFAULT AS IDENTITY ,
	login            VARCHAR (255) 	   NOT NULL ,
	password         VARCHAR (255) 	   NOT NULL  ,
	PRIMARY KEY (idtilisateur)
);


------------------------------------------------------------
-- Table: Bénévole
------------------------------------------------------------
CREATE TABLE benevole(
	idbenevole        INT 		 GENERATED BY DEFAULT AS IDENTITY ,
	idutilisateur    INT  NOT NULL  ,
	nom               VARCHAR (255) NOT NULL ,
	prenom            VARCHAR (255) NOT NULL ,
	age               INT  NOT NULL ,
	permis_conduire   VARCHAR (255) NOT NULL ,
	mineurs           BOOL  NOT NULL ,
	permanent         BOOL  NOT NULL ,
	
	PRIMARY KEY (idbenevole),
	
	FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur)
);


------------------------------------------------------------
-- Table: Poste
------------------------------------------------------------
CREATE TABLE poste(
	idposte        INT 		 GENERATED BY DEFAULT AS IDENTITY,
	lieu           VARCHAR (255) NOT NULL ,
	signaleur      BOOL  NOT NULL ,
	horaires       TIME  NOT NULL ,
	numero_poste   INT  NOT NULL  ,
	
	PRIMARY KEY (idposte)
);


------------------------------------------------------------
-- Table: Equipe
------------------------------------------------------------
CREATE TABLE equipe(
	idequipe     INT 		 GENERATED BY DEFAULT AS IDENTITY,
	nom_equipe   VARCHAR (255) NOT NULL ,
	
	PRIMARY KEY (idequipe)
);


------------------------------------------------------------
-- Table: Epreuve
------------------------------------------------------------
CREATE TABLE epreuve(
	idepreuve    INT 		 GENERATED BY DEFAULT AS IDENTITY,
	nom          VARCHAR (255) NOT NULL ,
	date_epreuve        DATE  NOT NULL ,
	lieu         VARCHAR (255) NOT NULL  ,
	
	PRIMARY KEY (ID_Epreuve)
);


------------------------------------------------------------
-- Table: Participant
------------------------------------------------------------
CREATE TABLE participant(
	idarticipant        INT 		 GENERATED BY DEFAULT AS IDENTITY,
	idequipe            INT  NOT NULL ,
	idepreuve           INT  NOT NULL ,
	idutilisateur       INT  NOT NULL  ,
	nom                 VARCHAR (255) NOT NULL ,
	prenom              VARCHAR (255) NOT NULL ,
	age                 INT  NOT NULL ,
	sexe                VARCHAR (255) NOT NULL ,
	numero_tel          VARCHAR (255) NOT NULL ,
	date_naissance      DATE  NOT NULL ,
	adresse             VARCHAR (255) NOT NULL ,
	role                VARCHAR (255) NOT NULL ,
	certifcat_medical   VARCHAR (255) NOT NULL ,
	mail                VARCHAR (255) NOT NULL ,
	niveau              VARCHAR (255) NOT NULL ,
	materiel_utilise    VARCHAR (255) NOT NULL ,
	nb_plateaux         INT  NOT NULL ,
	
	PRIMARY KEY (idparticipant),
	
	FOREIGN KEY (dequipe) REFERENCES utilisateur (idequipe),
	FOREIGN KEY (idepreuve) REFERENCES utilisateur (idepreuve),
	FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur)

);


------------------------------------------------------------
-- Table: Documents Licencies
------------------------------------------------------------
CREATE TABLE documents_licencies(
	iddocument       INT 		 GENERATED BY DEFAULT AS IDENTITY,
	id_participant   INT  NOT NULL  ,
	nom_doc          VARCHAR (255) NOT NULL ,
	date_doc         DATE  NOT NULL ,
	doc              VARCHAR (255) NOT NULL ,
	
	PRIMARY KEY (id_document),
	
	FOREIGN KEY (idparticipant) REFERENCES participant (idparticipant),

	UNIQUE (participant)
);


------------------------------------------------------------
-- Table: Avoir
------------------------------------------------------------
CREATE TABLE avoir(
	idposte      INT  NOT NULL ,
	idbenevole   INT  NOT NULL  ,
	
	-- CHECK( Role IN ('POSTE','BENEVOLE') ),
	
	PRIMARY KEY (idposte,idbenevole),
	
	FOREIGN KEY (idposte) REFERENCES poste (idposte),
	FOREIGN KEY (idbenevole) REFERENCES benevole (idbenevole),

);


------------------------------------------------------------
-- Table: Encadrer
------------------------------------------------------------
CREATE TABLE encadrer(
	idepreuve    INT  NOT NULL,
	idbenevole   INT  NOT NULL,
	
	PRIMARY KEY (idepreuve,idbenevole),
	
	FOREIGN KEY (idepreuve) REFERENCES epreuve (idepreuve),
	FOREIGN KEY (idbenevole) REFERENCES benveole (idbenevole)
);

*/

-- Vues

CREATE VIEW v_compte_avec_roles AS
	SELECT c.*, ARRAY_AGG( r.role ) AS roles
	FROM compte c
	LEFT JOIN ROLE r ON c.idcompte = r.idcompte
	GROUP BY c.idcompte;
